In [2]:
import pandas as pd
df = pd.read_csv("../data/mfrc/mini_mfrc.csv", index_col=0)
df.head()

,text_id,annotator_id,text,Authority,Care,Equality,Loyalty,Non-Moral,Proportionality,Purity,...,con_traditional,con_family,con_patriotism,social_conservatism,con_limited_government,con_welfare,con_gun,con_fiscal,con_business,economical_conservatism
0,dbv74ya_INCAS_random,25cirillow,Hollande put the country into a state of emerg...,0,0,0,1,0,0,0,...,50.0,100.0,10.0,61.428571,50.0,100.0,0.0,20.0,0.0,66.0
1,dbv74ya_INCAS_random,agwong,Hollande put the country into a state of emerg...,0,0,1,0,0,0,0,...,67.0,100.0,60.0,23.714286,72.0,72.0,0.0,82.0,83.0,38.2
2,dbv74ya_INCAS_random,akhlifat1413,Hollande put the country into a state of emerg...,0,0,1,0,0,0,0,...,93.0,87.0,93.0,14.714286,50.0,83.0,0.0,71.0,77.0,43.8
3,dbv74ya_INCAS_random,artakhosravi,Hollande put the country into a state of emerg...,1,0,1,1,0,0,0,...,35.0,40.0,20.0,59.285714,60.0,65.0,10.0,60.0,60.0,49.0
4,dbv74ya_INCAS_random,asapkota,Hollande put the country into a state of emerg...,1,0,0,0,0,0,0,...,30.0,55.0,58.0,46.857143,42.0,91.0,0.0,69.0,60.0,47.6

In [3]:
df.columns

Index(['text_id', 'annotator_id', 'text', 'Authority', 'Care', 'Equality',
       'Loyalty', 'Non-Moral', 'Proportionality', 'Purity', 'Thin Morality',
       'age', 'sex', 'sexualorientation', 'race', 'religion', 'religiosity_1',
       'care', 'equality', 'proportionality', 'authority', 'loyalty', 'purity',
       'extraversion', 'sociability', 'agreeableness', 'energy level',
       'compassion', 'respectfulness', 'trust', 'conscientiousness',
       'organization', 'productiveness', 'responsibility',
       'negative emotionality', 'anxiety', 'depression',
       'emotional volatility', 'open-mindedness', 'aesthetic sensitivity',
       'intellectual curiosity', 'creative imagination', 'tightness',
       'collectivism', 'individualism', 'con_abortion', 'con_military',
       'con_religion', 'con_marriage', 'con_traditional', 'con_family',
       'con_patriotism', 'social_conservatism', 'con_limited_government',
       'con_welfare', 'con_gun', 'con_fiscal', 'con_business',
       'economical_conservatism'],
      dtype='object')

In [4]:
df_filtered = df[['text_id', 'annotator_id', 'text', 'Non-Moral']]
df_filtered['Moral'] = df_filtered['Non-Moral'].apply(lambda x: 1 if x == 0 else 0)
df_filtered.head()
df_filtered.groupby('annotator_id')['Moral'].value_counts().reset_index(name='count')

/tmp/ipykernel_2974028/119667263.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['Moral'] = df_filtered['Non-Moral'].apply(lambda x: 1 if x == 0 else 0)

           annotator_id  Moral  count
0            25cirillow      1   1752
1            25cirillow      0    213
2       AAronvalencia13      1     84
3       AAronvalencia13      0     15
4       aaronvalencia13      1    484
5       aaronvalencia13      0     55
6                agwong      1   1345
7                agwong      0    651
8          akhlifat1413      1   1179
9          akhlifat1413      0    774
10         artakhosravi      1   1028
11         artakhosravi      0    966
12             asapkota      1   1428
13             asapkota      0    500
14              bahearn      1   1146
15              bahearn      0    829
16  christinamerrifield      1   1099
17  christinamerrifield      0    901
18           cynicaline      1   1426
19           cynicaline      0    572
20        evanabdollahi      1   1843
21        evanabdollahi      0    146
22          evannahasan      1   1341
23          evannahasan      0    563
24             evansalv      0   1048
25             evansalv      1    868
26               grantg      0   1030
27               grantg      1    926
28          hanachoi317      1   1162
29          hanachoi317      0    788
30         hardeepkaur6      1   1718
31         hardeepkaur6      0    267
32              jlitwin      0   1363
33              jlitwin      1    612
34          kelseycheng      0   1489
35          kelseycheng      1    472
36              kkroeck      0   1500
37              kkroeck      1    498
38               lauren      1   1006
39               lauren      0    796
40               mellow      1   1701
41               mellow      0    276
42                ntieu      1   1212
43                ntieu      0    774
44             phfang10      1   1229
45             phfang10      0    733
46             rahilcha      1   1762
47             rahilcha      0    225
48            sarahkang      1   1864
49            sarahkang      0    131
50             victoria      0    723
51             victoria      1    622
52              xiayuli      0   1149
53              xiayuli      1    847

In [5]:
df_filtered.groupby('annotator_id').count().reset_index().sort_values(by='text_id', ascending=False)
# df_filtered['annotator_id'].nunique()

           annotator_id  text_id  text  Non-Moral  Moral
8   christinamerrifield     2000  2000       2000   2000
9            cynicaline     1998  1998       1998   1998
18              kkroeck     1998  1998       1998   1998
26              xiayuli     1996  1996       1996   1996
3                agwong     1996  1996       1996   1996
24            sarahkang     1995  1995       1995   1995
5          artakhosravi     1994  1994       1994   1994
10        evanabdollahi     1989  1989       1989   1989
23             rahilcha     1987  1987       1987   1987
21                ntieu     1986  1986       1986   1986
15         hardeepkaur6     1985  1985       1985   1985
20               mellow     1977  1977       1977   1977
7               bahearn     1975  1975       1975   1975
16              jlitwin     1975  1975       1975   1975
0            25cirillow     1965  1965       1965   1965
22             phfang10     1962  1962       1962   1962
17          kelseycheng     1961  1961       1961   1961
13               grantg     1956  1956       1956   1956
4          akhlifat1413     1953  1953       1953   1953
14          hanachoi317     1950  1950       1950   1950
6              asapkota     1928  1928       1928   1928
12             evansalv     1916  1916       1916   1916
11          evannahasan     1904  1904       1904   1904
19               lauren     1802  1802       1802   1802
25             victoria     1345  1345       1345   1345
2       aaronvalencia13      539   539        539    539
1       AAronvalencia13       99    99         99     99

In [6]:
exclude = ['aaronvalencia13', 'AAronvalencia13', 'victoria']
df_filtered = df_filtered[~df_filtered['annotator_id'].isin(exclude)]
df_filtered['annotator_id'].nunique()
df_filtered = df_filtered[['text_id', 'annotator_id', 'text', 'Moral']]
df_filtered['ann_id'] = pd.factorize(df_filtered['annotator_id'])[0]

### split train test dev and save for each annotator

In [7]:
from sklearn.model_selection import train_test_split
seed = 0

text_ids = df_filtered['text_id'].unique().tolist()
train_ids, test_ids = train_test_split(text_ids, test_size=0.2, random_state=seed)
val_ids, test_ids = train_test_split(test_ids, test_size=0.5, random_state=seed)
len(train_ids), len(test_ids), len(val_ids)

(1600, 200, 200)

In [8]:
train_df = df_filtered[df_filtered['text_id'].isin(train_ids)]
val_df = df_filtered[df_filtered['text_id'].isin(val_ids)]
test_df = df_filtered[df_filtered['text_id'].isin(test_ids)]

train_df.groupby('annotator_id')['Moral'].value_counts().reset_index(name='count')

           annotator_id  Moral  count
0            25cirillow      1   1415
1            25cirillow      0    159
2                agwong      1   1084
3                agwong      0    512
4          akhlifat1413      1    947
5          akhlifat1413      0    621
6          artakhosravi      1    817
7          artakhosravi      0    777
8              asapkota      1   1153
9              asapkota      0    386
10              bahearn      1    931
11              bahearn      0    648
12  christinamerrifield      1    894
13  christinamerrifield      0    706
14           cynicaline      1   1157
15           cynicaline      0    441
16        evanabdollahi      1   1484
17        evanabdollahi      0    107
18          evannahasan      1   1096
19          evannahasan      0    423
20             evansalv      0    830
21             evansalv      1    702
22               grantg      0    806
23               grantg      1    759
24          hanachoi317      1    940
25          hanachoi317      0    619
26         hardeepkaur6      1   1379
27         hardeepkaur6      0    207
28              jlitwin      0   1086
29              jlitwin      1    493
30          kelseycheng      0   1183
31          kelseycheng      1    390
32              kkroeck      0   1202
33              kkroeck      1    397
34               lauren      1    811
35               lauren      0    633
36               mellow      1   1372
37               mellow      0    210
38                ntieu      1    982
39                ntieu      0    606
40             phfang10      1    999
41             phfang10      0    571
42             rahilcha      1   1416
43             rahilcha      0    171
44            sarahkang      1   1496
45            sarahkang      0     99
46              xiayuli      0    907
47              xiayuli      1    690

In [9]:
import os
label = 'Moral'
path = f'../data/mfrc/{label}/annotators'
os.makedirs(path, exist_ok=True)
for ann in df_filtered['ann_id'].unique():
    ann_path = f'{path}/{ann}'
    os.makedirs(ann_path, exist_ok=True)
    df_train = train_df[train_df['ann_id'] == ann]
    df_val = val_df[val_df['ann_id'] == ann]
    df_test = test_df[test_df['ann_id'] == ann]
    print(ann , len(df_train), len(df_val), len(df_test))
    # df_train.to_csv(f'{path}/{ann}/train.csv')
    # df_val.to_csv(f'{path}/{ann}/val.csv')
    # df_test.to_csv(f'{path}/{ann}/test.csv')

0 1574 195 196
1 1596 200 200
2 1568 191 194
3 1594 200 200
4 1539 193 196
5 1579 197 199
6 1600 200 200
7 1598 200 200
8 1591 199 199
9 1519 192 193
10 1532 192 192
11 1565 194 197
12 1559 197 194
13 1586 200 199
14 1579 196 200
15 1573 196 192
16 1599 199 200
17 1444 177 181
18 1582 197 198
19 1588 199 199
20 1570 196 196
21 1587 200 200
22 1595 200 200
23 1597 200 199

In [36]:
df_filtered

,text_id,annotator_id,text,Non-Moral,Moral
0,dbv74ya_INCAS_random,25cirillow,Hollande put the country into a state of emerg...,0,1
1,dbv74ya_INCAS_random,agwong,Hollande put the country into a state of emerg...,0,1
2,dbv74ya_INCAS_random,akhlifat1413,Hollande put the country into a state of emerg...,0,1
3,dbv74ya_INCAS_random,artakhosravi,Hollande put the country into a state of emerg...,0,1
4,dbv74ya_INCAS_random,asapkota,Hollande put the country into a state of emerg...,0,1
...,...,...,...,...,...
49125,glgexsg_everyday_random,ntieu,What does she get out of it..? Like plenty of...,0,1
49126,glgexsg_everyday_random,phfang10,What does she get out of it..? Like plenty of...,0,1
49127,glgexsg_everyday_random,rahilcha,What does she get out of it..? Like plenty of...,0,1
49128,glgexsg_everyday_random,sarahkang,What does she get out of it..? Like plenty of...,0,1
49130,glgexsg_everyday_random,xiayuli,What does she get out of it..? Like plenty of...,0,1